apiVersion: v1
kind: Pod
metadata:
  name: game-login-pod
  labels:
    app: game-login
spec:
  containers:
  - name: login-container
    image: registry.cn-shenzhen.aliyuncs.com/amgs/nginx:latest
    imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk-type
            operator: In
            values:
            - ssd